version: '3.8'
services:
  mysql:
    image: mariadb:10.3.23
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
    - 3307:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "getDB", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  login-api:
    image: library/openjdk:11
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-login-api/build/libs:/home/eatgo/libs
    ports:
      - 8001:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"

  admin-api:
    image: library/openjdk:11
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-admin-api/build/libs:/home/eatgo/libs
    ports:
      - 8002:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"

  customer-api:
    image: library/openjdk:11
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-customer-api/build/libs:/home/eatgo/libs
    ports:
      - 8003:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"

  restaurant-api:
    image: library/openjdk:11
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-restaurant-api/build/libs:/home/eatgo/libs
    ports:
      - 8004:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
