spring:
  datasource:
      jdbc-url: jdbc:mariadb://localhost:3306/eatgo
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1340mses
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
